### ISSUE TITLE
Support Jakarta EE 10

### ISSUE THREAD

**Issue by Thopap** [prolutionsGmbH/herasaf-xacml-core#13]
Currently heras-xacml use the jaxb-api from the javax.xml.bind namespace (J2EE 8). To allow the usage of Heras also with J2EE 10+ compatible applications an update to jakarta xml-bind 4.0 should be done (which use the package jakarta.xml.bind for the jaxb annotations).

Since this change will introduce a incompatible change, a Heras 3.x version is needed.

**Comment by fhuonder** [comment]
Hi @Thopap 

I agree that we should create a version 3.x that is J2EE 10+ and keep the version 2.x for J2EE 8 (as long as needed).
Because we are very short on time it would be greate if you could create a PR. I will then be very happy to review and create a new release.

**Comment by Thopap** [comment]
This was already the my plan to provide a PR :-)  I was just not able to assign this ticket to myself.

**Comment by fhuonder** [comment]
done in pr #14

**Comment by fhuonder** [comment]
I am going to release a new version (3.0.0) this week ...

**Comment by fhuonder** [comment]
Release is created (https://github.com/prolutionsGmbH/herasaf-xacml-core/releases/tag/3.0.2) and available from maven central.
Have fun ...
