### ISSUE TITLE
AnyUri Datatype do not permit a empty AttributeValue

### ISSUE THREAD

**Issue by Thopap** [prolutionsGmbH/herasaf-xacml-core#7]
According to XACML 2.0 chapter 6.8 a AttributeValue can be empty. Since a empty attribute value is not possible for all datatype's, the range is limited here. Currently Heras allow a empty attribute Value only for "XMLSchema#string".

But for XMLSchema#anyURI, a empty value is also a valid value as URI (e.g. see here http://www.datypic.com/sc/xsd/t-xsd_anyURI.html).

Given the following attribute definition in a XACML context:
`	<Subject>
		<Attribute
			AttributeId="urn:oasis:names:tc:xacml:2.0:subject:role"
			DataType="http://www.w3.org/2001/XMLSchema#anyURI">
			<AttributeValue></AttributeValue>
		</Attribute>
	</Subject>`

**The current behavior:**
... Is a syntax error and a indeterminate result of the authorization request.

**Expected behavior**
... the processing continue with a value empty Uri.

**Comment by fhuonder** [comment]
@Thopap 
Fixed in version 2.0.4 (available from Maven Central)
